export const markets = ['Bariatrics', 'Dermatology', 'Neurology', 'NHR', 'Oncology', 'Ophthalmology', 'Other'];
export const clients = [
    'AbbVie Skyrizi',
    'AbbVie/Rinvoq',
    'Amgen/Uplizna',
    'Arcutis/Zoryve',
    'AZ/Calquence',
    'AZ/Imfinzi',
    'AZ/One Lung',
    'AZ/Tagrisso',
    'AZ/Truqap',
    'Beiersdorf/Body',
    'Beiersdorf/Eczema',
    'BI/Spevigo',
    'BMS/Breyansi',
    'Castle',
    'Exelixis/Cabometyx',
    'Genentech/Vabysmo',
    'Incyte/Opzelura',
    'J&J/Carvykti',
    'Lilly/Kisunla',
    'Lilly/Verzenio',
    'Medtronic/Signia',
    'None',
    'Ortho/Cabtreo',
    'Skinbetter',
    'Skinceuticals',
    'Sun/Winlevi'
];

export const projects = [
    'Biorewind Video Project',
    'BT',
    'Conf Cov: AAD 2025',
    'Conf Cov: AAD 2025 Summer',
    'Conf Cov: MD NPPA Fall',
    'CU Breast Cancer',
    'CU GPP',
    'CU Unsponsored',
    'Custom Email',
    'EP AD',
    'EP GPP',
    'EP Melanoma/SCC',
    'EP NET',
    'EP PIA',
    'EP RCC',
    'EP Therapeutic Skincare',
    'EP VIT',
    'Hot Topics- Derm',
    'Hot Topics- Neurology',
    'Hot Topics- Oncology',
    'ICNS',
    'JCAD Journal',
    'JCADTV Unsponsored',
    'NHR',
    'NPPA/PIA',
    'Patient Edition',
    'Triggered Email'
];